use rkg_utils::header::{mii::favorite_color::FavoriteColor, slot_id::SlotId};

pub fn track_abbreviation(slot_id: SlotId) -> String {
    match slot_id {
        SlotId::LuigiCircuit => String::from("LC"),
        SlotId::MooMooMeadows => String::from("MMM"),
        SlotId::MushroomGorge => String::from("MG"),
        SlotId::ToadsFactory => String::from("TF"),
        SlotId::MarioCircuit => String::from("MC"),
        SlotId::CoconutMall => String::from("CM"),
        SlotId::DKSnowboardCross => String::from("DKSC"),
        SlotId::WariosGoldMine => String::from(String::from("WGM")),
        SlotId::DaisyCircuit => String::from(String::from("DC")),
        SlotId::KoopaCape => String::from(String::from("KC")),
        SlotId::MapleTreeway => String::from(String::from("MT")),
        SlotId::GrumbleVolcano => String::from(String::from("GV")),
        SlotId::DryDryRuins => String::from(String::from("DDR")),
        SlotId::MoonviewHighway => String::from(String::from("MH")),
        SlotId::BowsersCastle => String::from(String::from("BC")),
        SlotId::RainbowRoad => String::from(String::from("RR")),
        SlotId::GCNPeachBeach => String::from(String::from("rPB")),
        SlotId::DSYoshiFalls => String::from(String::from("rYF")),
        SlotId::SNESGhostValley2 => String::from(String::from("rGV2")),
        SlotId::N64MarioRaceway => String::from(String::from("rMR")),
        SlotId::N64SherbetLand => String::from(String::from("rSL")),
        SlotId::GBAShyGuyBeach => String::from(String::from("rSGB")),
        SlotId::DSDelfinoSquare => String::from(String::from("rDS")),
        SlotId::GCNWaluigiStadium => String::from(String::from("rWS")),
        SlotId::DSDesertHills => String::from(String::from("rDH")),
        SlotId::GBABowserCastle3 => String::from(String::from("rBC3")),
        SlotId::N64DKJungleParkway => String::from(String::from("rDKJP")),
        SlotId::GCNMarioCircuit => String::from(String::from("rMC")),
        SlotId::SNESMarioCircuit3 => String::from(String::from("rMC3")),
        SlotId::DSPeachGardens => String::from(String::from("rPG")),
        SlotId::GCNDKMountain => String::from(String::from("rDKM")),
        SlotId::N64BowsersCastle => String::from(String::from("rBC")),
        SlotId::BlockPlaza => String::from(String::from("bBP")),
        SlotId::DelfinoPier => String::from(String::from("bDP")),
        SlotId::FunkyStadium => String::from(String::from("bFS")),
        SlotId::ChainChompWheel => String::from(String::from("bCCW")),
        SlotId::ThwompDesert => String::from(String::from("bTD")),
        SlotId::SNESBattleCourse4 => String::from(String::from("brBC4")),
        SlotId::GBABattleCourse3 => String::from(String::from("brBC3")),
        SlotId::N64Skscraper => String::from(String::from("brS")),
        SlotId::GCNCookieLand => String::from(String::from("brCL")),
        SlotId::DSTwilightHouse => String::from(String::from("brTH")),
        SlotId::GalaxyColosseum => String::from(String::from("GC")),
        SlotId::WinningScene => String::from(String::from("WS")),
        SlotId::LosingScene => String::from(String::from("LS")),
        SlotId::Credits => String::from(String::from("C")),
    }
}

pub fn favorite_color_string(f: FavoriteColor) -> String {
    match f {
        FavoriteColor::Red => String::from("Red"),
        FavoriteColor::Orange => String::from("Orange"),
        FavoriteColor::Yellow => String::from("Yellow"),
        FavoriteColor::LimeGreen => String::from("Light Green"),
        FavoriteColor::ForestGreen => String::from("Green"),
        FavoriteColor::RoyalBlue => String::from("Blue"),
        FavoriteColor::SkyBlue => String::from("Light Blue"),
        FavoriteColor::Pink => String::from("Pink"),
        FavoriteColor::Purple => String::from("Purple"),
        FavoriteColor::Brown => String::from("Brown"),
        FavoriteColor::White => String::from("White"),
        FavoriteColor::Black => String::from("Black"),
    }
}
